# Generated by Django 4.1.7 on 2023-02-16 02:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='alternate_name',
        ),
        migrations.AlterField(
            model_name='account',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Whether tag is approved'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Last time the rank information was refreshed'),
        ),
        migrations.AlterField(
            model_name='account',
            name='slippi_tag',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(code='invalid_slippi_tag', message='Invalid Slippi Tag', regex='^[a-zA-Z0-9]*$')], verbose_name='Slippi Tag to register'),
        ),
    ]
