# Generated by Django 4.1.7 on 2023-02-16 04:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import leaderboard.models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_remove_account_alternate_name_alter_account_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='slippi_tag',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(code='invalid_slippi_tag', message='Invalid Slippi Tag. \n                Must be up to 8 Alphanumerals \n                followed by a "#" and up to 4 digits', regex='^[A-Z0-9]{1,8}#[0-9]{1,4}$'), leaderboard.models.validate_slippi_tag], verbose_name='Slippi Tag to register'),
        ),
        migrations.CreateModel(
            name='AccountUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now_add=True, verbose_name='When the update occurred')),
                ('slippi_data', models.JSONField(verbose_name='Data returned by the slippi api')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.account')),
            ],
        ),
    ]
