# Generated by Django 4.1.7 on 2023-02-19 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0007_remove_accountupdate_slippi_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('characters', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_updated',
        ),
        migrations.DeleteModel(
            name='AccountUpdate',
        ),
        migrations.AddField(
            model_name='update',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leaderboard.account'),
        ),
        migrations.AddField(
            model_name='account',
            name='current_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leaderboard.update'),
        ),
        migrations.AddField(
            model_name='account',
            name='previous_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leaderboard.update'),
        ),
    ]
