# Generated by Django 4.1.7 on 2023-02-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0008_update_remove_account_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='ranking',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
