# Generated by Django 4.1.7 on 2023-02-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slippi_tag', models.CharField(max_length=40, verbose_name='Slippi Tag to register')),
                ('approved', models.BooleanField(default=True, verbose_name='Whether tag is approved')),
                ('alternate_name', models.CharField(max_length=40, verbose_name='Alternative name to display')),
                ('last_updated', models.DateTimeField(verbose_name='Last time the rank information was refreshed')),
            ],
        ),
    ]
